package com.jshop.entity;

// Generated 2012-10-10 12:34:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AdvertiseT generated by hbm2java
 */
public class AdvertiseT implements java.io.Serializable {

	private String id;
	private String type;
	private String advPath;
	private String showPosition;
	private int showAmount;
	private double showCount;
	private String showWhere;
	private String alt;
	private Date begintime;
	private Date endtime;
	private Date createtime;
	private String creatorid;
	private String state;

	public AdvertiseT() {
	}

	public AdvertiseT(String id, String type, String advPath,
			String showPosition, int showAmount, double showCount,
			String showWhere, String alt, Date begintime, Date endtime,
			Date createtime, String creatorid, String state) {
		this.id = id;
		this.type = type;
		this.advPath = advPath;
		this.showPosition = showPosition;
		this.showAmount = showAmount;
		this.showCount = showCount;
		this.showWhere = showWhere;
		this.alt = alt;
		this.begintime = begintime;
		this.endtime = endtime;
		this.createtime = createtime;
		this.creatorid = creatorid;
		this.state = state;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getAdvPath() {
		return this.advPath;
	}

	public void setAdvPath(String advPath) {
		this.advPath = advPath;
	}

	public String getShowPosition() {
		return this.showPosition;
	}

	public void setShowPosition(String showPosition) {
		this.showPosition = showPosition;
	}

	public int getShowAmount() {
		return this.showAmount;
	}

	public void setShowAmount(int showAmount) {
		this.showAmount = showAmount;
	}

	public double getShowCount() {
		return this.showCount;
	}

	public void setShowCount(double showCount) {
		this.showCount = showCount;
	}

	public String getShowWhere() {
		return this.showWhere;
	}

	public void setShowWhere(String showWhere) {
		this.showWhere = showWhere;
	}

	public String getAlt() {
		return this.alt;
	}

	public void setAlt(String alt) {
		this.alt = alt;
	}

	public Date getBegintime() {
		return this.begintime;
	}

	public void setBegintime(Date begintime) {
		this.begintime = begintime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getCreatorid() {
		return this.creatorid;
	}

	public void setCreatorid(String creatorid) {
		this.creatorid = creatorid;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
