package com.jshop.entity;

// Generated 2012-10-10 12:34:32 by Hibernate Tools 3.4.0.CR1

/**
 * GoodsTwocodeRelationshipT generated by hbm2java
 */
public class GoodsTwocodeRelationshipT implements java.io.Serializable {

	private String id;
	private String goodsid;
	private String goodsname;
	private String twocodepath;
	private String state;

	public GoodsTwocodeRelationshipT() {
	}

	public GoodsTwocodeRelationshipT(String id, String goodsid,
			String goodsname, String twocodepath, String state) {
		this.id = id;
		this.goodsid = goodsid;
		this.goodsname = goodsname;
		this.twocodepath = twocodepath;
		this.state = state;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getGoodsid() {
		return this.goodsid;
	}

	public void setGoodsid(String goodsid) {
		this.goodsid = goodsid;
	}

	public String getGoodsname() {
		return this.goodsname;
	}

	public void setGoodsname(String goodsname) {
		this.goodsname = goodsname;
	}

	public String getTwocodepath() {
		return this.twocodepath;
	}

	public void setTwocodepath(String twocodepath) {
		this.twocodepath = twocodepath;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
